import argparse
import logging
import sys
from pathlib import Path

sys.path.append("src")

import numpy as np
import torch
from torch.utils.data import DataLoader

from src.config_utils import ensure_dir, load_config
from src.logging_utils import configure_logging
from src.mlflow_utils import MLflowTracker
from src.oceantaco import batch_to_model_tensors, build_dataset, get_collate_fn, prediction_records
from src.simvp_model import SimVP_Model_no_skip_configurable

LOGGER = logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(description="Run SimVP inference on an OceanTACO split.")
    parser.add_argument(
        "--config",
        default="configs/oceantaco.yaml",
        help="Path to the YAML configuration file.",
    )
    parser.add_argument(
        "--checkpoint",
        required=True,
        help="Checkpoint generated by simvp_ddp_training.py.",
    )
    parser.add_argument(
        "--split",
        default=None,
        help="Override the configured prediction split.",
    )
    return parser.parse_args()


def build_model(config):
    grid_cfg = config["data"]["grid"]
    model_cfg = config["model"]
    sequence_length = int(config["data"]["sequence_length"])
    input_channels = len(config["data"]["inputs"])
    target_channels = len(config["data"]["targets"])

    return SimVP_Model_no_skip_configurable(
        in_shape=(sequence_length, input_channels, int(grid_cfg["height"]), int(grid_cfg["width"])),
        out_channels=target_channels,
        model_type=model_cfg["type"],
        hid_S=int(model_cfg["hidden_spatial"]),
        hid_T=int(model_cfg["hidden_temporal"]),
        N_S=int(model_cfg["spatial_depth"]),
        N_T=int(model_cfg["temporal_depth"]),
        drop=float(model_cfg["drop"]),
        drop_path=float(model_cfg["drop_path"]),
    )


def nonempty_target_mask(targets: torch.Tensor) -> torch.Tensor:
    # A target is considered empty if every value across time/channel/grid is
    # zero. This matches the current loader behavior, where missing/NaN values
    # are normalized into zero-filled tensors.
    flattened = targets.reshape(targets.shape[0], -1)
    return torch.any(flattened != 0, dim=1)


def main():
    args = parse_args()
    config = load_config(args.config)
    configure_logging(config)
    prediction_cfg = config["prediction"]
    split_name = args.split or prediction_cfg["split"]
    tracker = MLflowTracker(config, stage="prediction")
    LOGGER.info("Loaded prediction config from %s", config["__config_path__"])

    tracker.start_run(
        run_name=prediction_cfg.get("run_name"),
        extra_tags={"split": split_name, "checkpoint": str(Path(args.checkpoint).name)},
    )
    try:
        dataset = build_dataset(config, split_name)
        if len(dataset) == 0:
            raise RuntimeError(f"No OceanTACO samples matched split '{split_name}'.")
        LOGGER.info("Loaded prediction dataset for split=%s with %s samples", split_name, len(dataset))

        dataloader = DataLoader(
            dataset,
            batch_size=int(prediction_cfg["batch_size"]),
            shuffle=False,
            num_workers=int(config["training"]["num_workers"]),
            collate_fn=get_collate_fn(),
        )

        output_dir = ensure_dir(config["paths"]["predictions_dir"], config)
        checkpoint = torch.load(Path(args.checkpoint), map_location="cpu")
        LOGGER.info("Writing predictions to %s", output_dir)
        LOGGER.info("Loaded checkpoint from %s", args.checkpoint)
        tracker.log_config()
        tracker.log_metrics({"prediction_dataset_size": float(len(dataset))}, step=0)
        tracker.log_artifact(args.checkpoint, artifact_subdir="checkpoints")

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = build_model(config).to(device)
        model.load_state_dict(checkpoint["model_state_dict"])
        model.eval()
        LOGGER.info("Using device=%s for inference", device)

        saved_files = 0
        skipped_batches = 0
        zero_input_batches = 0
        skipped_empty_target_samples = 0
        allow_empty_inputs = bool(prediction_cfg.get("allow_empty_inputs", True))
        with torch.no_grad():
            for batch_index, batch in enumerate(dataloader):
                print(f"BATCH: ", batch)
                has_any_inputs = any(tensor is not None for tensor in batch["inputs"].values())
                inputs, targets = batch_to_model_tensors(batch, config, allow_empty_inputs=allow_empty_inputs)
                print(f"Inputs: {inputs}, Targets: {targets}")
                print(f"Batch: {batch}, Config: {config}")
                if inputs is None:
                    skipped_batches += 1
                    LOGGER.warning("Skipping empty prediction batch %s/%s", batch_index + 1, len(dataloader))
                    continue
                if not has_any_inputs:
                    zero_input_batches += 1
                    LOGGER.warning(
                        "Prediction batch %s/%s has no observed inputs. Using zero-filled tensors instead.",
                        batch_index + 1,
                        len(dataloader),
                    )
                records = prediction_records(batch, config)
                valid_target_mask = nonempty_target_mask(targets)
                skipped_in_batch = int((~valid_target_mask).sum().item())
                if skipped_in_batch:
                    skipped_empty_target_samples += skipped_in_batch
                    LOGGER.warning(
                        "Skipping %s empty-target samples in prediction batch %s/%s",
                        skipped_in_batch,
                        batch_index + 1,
                        len(dataloader),
                    )
                if not bool(valid_target_mask.any()):
                    skipped_batches += 1
                    LOGGER.warning(
                        "Skipping prediction batch %s/%s because every target sample is empty.",
                        batch_index + 1,
                        len(dataloader),
                    )
                    continue

                inputs = inputs[valid_target_mask]
                targets = targets[valid_target_mask]
                records = [record for record, keep in zip(records, valid_target_mask.tolist()) if keep]
                inputs = inputs.to(device)
                predictions = model(inputs).cpu().numpy()
                targets = targets.numpy()

                batch_size = predictions.shape[0]
                for sample_index in range(batch_size):
                    record = records[sample_index]
                    lon_min, lon_max, lat_min, lat_max = record["bbox"]
                    target_date = record["target_date"]
                    save_path = output_dir / (
                        f"{split_name}_{target_date}_"
                        f"lon{lon_min:.2f}_{lon_max:.2f}_lat{lat_min:.2f}_{lat_max:.2f}.npz"
                    )
                    np.savez_compressed(
                        save_path,
                        prediction=predictions[sample_index],
                        target=targets[sample_index],
                        bbox=np.array(record["bbox"], dtype=np.float32),
                        time_range=np.array(record["time_range"]),
                        target_date=target_date,
                    )
                    saved_files += 1
                    if config.get("tracking", {}).get("mlflow", {}).get("log_prediction_artifacts", False):
                        tracker.log_artifact(save_path, artifact_subdir="predictions")
                LOGGER.info(
                    "Saved prediction batch %s/%s with %s samples",
                    batch_index + 1,
                    len(dataloader),
                    batch_size,
                )
    finally:
        if "saved_files" in locals():
            tracker.log_metrics(
                {
                    "saved_prediction_files": float(saved_files),
                    "skipped_prediction_batches": float(skipped_batches),
                    "zero_input_prediction_batches": float(zero_input_batches),
                    "skipped_empty_target_samples": float(skipped_empty_target_samples),
                },
                step=0,
            )
            LOGGER.info(
                "Prediction run finished with saved_prediction_files=%s skipped_prediction_batches=%s "
                "zero_input_prediction_batches=%s skipped_empty_target_samples=%s",
                saved_files,
                skipped_batches,
                zero_input_batches,
                skipped_empty_target_samples,
            )
        tracker.end_run()


if __name__ == "__main__":
    main()
