import argparse
import copy
import csv
import json
import logging
import sys
from pathlib import Path

sys.path.append("src")

import numpy as np
import torch
from torch.utils.data import DataLoader

from src.config_utils import ensure_dir, load_config
from src.logging_utils import configure_logging
from src.mlflow_utils import MLflowTracker
from src.oceantaco import (
    batch_input_fields,
    batch_to_model_tensors,
    build_dataset,
    denormalise_tensor,
    get_collate_fn,
    prediction_records,
    split_uses_reserved_metrics,
)
from src.simvp_model import build_simvp_model_from_config, describe_model_config

LOGGER = logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(description="Run SimVP inference on an OceanTACO split.")
    parser.add_argument(
        "--config",
        default="configs/oceantaco.yaml",
        help="Path to the YAML configuration file.",
    )
    parser.add_argument(
        "--checkpoint",
        required=True,
        help="Checkpoint generated by simvp_ddp_training.py.",
    )
    parser.add_argument(
        "--split",
        default=None,
        help="Override the configured prediction split.",
    )
    return parser.parse_args()


def build_model(config):
    return build_simvp_model_from_config(config)


def nonempty_target_mask(targets: torch.Tensor) -> torch.Tensor:
    # A target is considered empty if every value across time/channel/grid is
    # zero. This matches the current loader behavior, where missing/NaN values
    # are normalized into zero-filled tensors.
    flattened = targets.reshape(targets.shape[0], -1)
    return torch.any(flattened != 0, dim=1)


def is_degenerate_input_field(field: np.ndarray) -> bool:
    finite = field[np.isfinite(field)]
    if finite.size == 0:
        return True

    finite_fraction = float(finite.size) / float(field.size)
    if finite_fraction < 0.1 and np.allclose(finite, 0.0):
        return True
    return False


def build_prediction_collate_fn():
    base_collate = get_collate_fn()

    def collate_with_raw_samples(batch):
        collated = base_collate(batch)
        collated["raw_samples"] = batch
        return collated

    return collate_with_raw_samples


def _as_single_sample_batch_tensor(tensor: torch.Tensor | None) -> torch.Tensor | None:
    if tensor is None:
        return None

    output = tensor.float()
    if output.ndim == 2:
        return output.unsqueeze(0)
    if output.ndim == 3:
        return output.unsqueeze(0)
    if output.ndim == 4:
        return output
    raise ValueError(f"Unsupported raw sample tensor shape: {tuple(output.shape)}")


def sample_plot_input_fields(sample: dict, config: dict) -> dict[str, torch.Tensor] | None:
    single_sample_batch = {
        "inputs": {
            variable_name: _as_single_sample_batch_tensor(None if payload is None else payload.get("data"))
            for variable_name, payload in sample.get("inputs", {}).items()
        },
        "targets": {
            variable_name: _as_single_sample_batch_tensor(None if payload is None else payload.get("data"))
            for variable_name, payload in sample.get("targets", {}).items()
        },
        "metadata": {
            "bboxes": [sample.get("metadata", {}).get("bbox")],
            "time_ranges": [sample.get("metadata", {}).get("time_range")],
        },
    }
    prepared = batch_input_fields(single_sample_batch, config, normalise=False, preserve_missing=True)
    if prepared is None:
        return None
    return {
        variable_name: tensor[0]
        for variable_name, tensor in prepared.items()
    }


def configured_input_keys(config: dict) -> list[str]:
    return [str(variable_cfg["key"]) for variable_cfg in config["data"]["inputs"]]


def infer_sample_input_statuses(sample: dict, config: dict) -> dict[str, dict[str, object]]:
    observed_fields = sample_plot_input_fields(sample, config)
    statuses: dict[str, dict[str, object]] = {}
    configured_keys = configured_input_keys(config)

    for variable_name in configured_keys:
        payload = sample.get("inputs", {}).get(variable_name)
        field = None if observed_fields is None else observed_fields.get(variable_name)
        is_configured = True
        if payload is None or payload.get("data") is None:
            dataset_status = "missing_from_dataset"
            model_status = "zero_filled_missing"
        elif field is None:
            dataset_status = "missing_from_dataset"
            model_status = "zero_filled_missing"
        else:
            field_array = field.detach().cpu().numpy()
            if np.isnan(field_array).all():
                dataset_status = "missing_from_dataset"
                model_status = "zero_filled_missing"
            elif is_degenerate_input_field(field_array):
                dataset_status = "degenerate"
                model_status = "zero_filled_degenerate"
            else:
                dataset_status = "observed"
                model_status = "observed"

        statuses[variable_name] = {
            "configured": is_configured,
            "dataset_status": dataset_status,
            "model_status": model_status,
            "field": field,
        }

    return statuses


def _load_checkpoint_training_config(checkpoint: dict) -> dict | None:
    config_snapshot = checkpoint.get("config_snapshot")
    if isinstance(config_snapshot, dict):
        return copy.deepcopy(config_snapshot)

    config_path = checkpoint.get("config_path")
    if not config_path:
        return None

    config_file = Path(config_path)
    if not config_file.exists():
        LOGGER.warning(
            "Checkpoint references training config %s, but that file is not available in this environment.",
            config_path,
        )
        return None
    return load_config(config_file)


def _merge_prediction_runtime_config(runtime_config: dict, checkpoint_config: dict | None) -> dict:
    effective_config = copy.deepcopy(runtime_config)
    if checkpoint_config is None:
        return effective_config

    for key in ("data", "model"):
        if key in checkpoint_config:
            effective_config[key] = copy.deepcopy(checkpoint_config[key])

    LOGGER.info(
        "Using data/model settings from checkpoint training config %s",
        checkpoint_config.get("__config_path__", "<embedded config snapshot>"),
    )
    return effective_config


def _denormalise_prediction_tensor(
    tensor: torch.Tensor,
    variable_configs: list[dict],
    *,
    preserve_zero_mask: bool,
) -> torch.Tensor:
    channel_tensors = []
    for channel_index, source_cfg in enumerate(variable_configs):
        channel = tensor[:, :, channel_index, :, :]
        channel_tensors.append(
            denormalise_tensor(channel, source_cfg, preserve_zero_mask=preserve_zero_mask)
        )
    return torch.stack(channel_tensors, dim=2)


class ReservedReferenceMetrics:
    def __init__(self, variable_name: str):
        self.variable_name = variable_name
        self.rows: list[dict[str, object]] = []
        self.sum_squared_error = 0.0
        self.sum_absolute_error = 0.0
        self.sum_prediction = 0.0
        self.sum_reference = 0.0
        self.sum_prediction_squared = 0.0
        self.sum_reference_squared = 0.0
        self.sum_prediction_reference = 0.0
        self.count = 0

    def update(self, prediction_2d: np.ndarray, reference_2d: np.ndarray, record: dict[str, object]) -> None:
        valid_mask = np.isfinite(prediction_2d) & np.isfinite(reference_2d) & (reference_2d != 0.0)
        valid_count = int(valid_mask.sum())
        if valid_count == 0:
            self.rows.append(
                {
                    "target_date": record["target_date"],
                    "bbox": record["bbox"],
                    "valid_pixels": 0,
                    "mae": np.nan,
                    "rmse": np.nan,
                    "bias": np.nan,
                }
            )
            return

        pred = prediction_2d[valid_mask].astype(np.float64)
        ref = reference_2d[valid_mask].astype(np.float64)
        diff = pred - ref
        squared_error = float(np.sum(diff * diff))
        absolute_error = float(np.sum(np.abs(diff)))

        self.sum_squared_error += squared_error
        self.sum_absolute_error += absolute_error
        self.sum_prediction += float(np.sum(pred))
        self.sum_reference += float(np.sum(ref))
        self.sum_prediction_squared += float(np.sum(pred * pred))
        self.sum_reference_squared += float(np.sum(ref * ref))
        self.sum_prediction_reference += float(np.sum(pred * ref))
        self.count += valid_count

        self.rows.append(
            {
                "target_date": record["target_date"],
                "bbox": record["bbox"],
                "valid_pixels": valid_count,
                "mae": absolute_error / valid_count,
                "rmse": float(np.sqrt(squared_error / valid_count)),
                "bias": float(np.mean(diff)),
            }
        )

    def summary(self) -> dict[str, float | int | str]:
        if self.count == 0:
            return {
                "variable": self.variable_name,
                "valid_pixels": 0,
                "mae": float("nan"),
                "rmse": float("nan"),
                "bias": float("nan"),
                "correlation": float("nan"),
            }

        prediction_mean = self.sum_prediction / self.count
        reference_mean = self.sum_reference / self.count
        covariance = self.sum_prediction_reference - self.count * prediction_mean * reference_mean
        prediction_var = self.sum_prediction_squared - self.count * prediction_mean * prediction_mean
        reference_var = self.sum_reference_squared - self.count * reference_mean * reference_mean
        denominator = np.sqrt(max(prediction_var, 0.0) * max(reference_var, 0.0))
        correlation = float(covariance / denominator) if denominator > 0 else float("nan")

        return {
            "variable": self.variable_name,
            "valid_pixels": self.count,
            "mae": self.sum_absolute_error / self.count,
            "rmse": float(np.sqrt(self.sum_squared_error / self.count)),
            "bias": (self.sum_prediction - self.sum_reference) / self.count,
            "correlation": correlation,
        }

    def write(self, output_dir: Path) -> dict[str, float | int | str]:
        summary = self.summary()
        csv_path = output_dir / f"reserved_{self.variable_name}_metrics.csv"
        json_path = output_dir / f"reserved_{self.variable_name}_metrics_summary.json"
        with csv_path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=["target_date", "bbox", "valid_pixels", "mae", "rmse", "bias"])
            writer.writeheader()
            writer.writerows(self.rows)
        with json_path.open("w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2, sort_keys=True)
        LOGGER.info("Saved reserved-reference metrics to %s and %s: %s", csv_path, json_path, summary)
        return summary


def build_reserved_reference_loader(config: dict, split_name: str, prediction_cfg: dict):
    if not split_uses_reserved_metrics(config, split_name):
        return None

    reference_dataset = build_dataset(config, split_name, reserved_filter_mode="only_reserved")
    if len(reference_dataset) == 0:
        LOGGER.warning("Reserved-reference dataset for split=%s is empty; metrics will be skipped.", split_name)
        return None

    return DataLoader(
        reference_dataset,
        batch_size=int(prediction_cfg["batch_size"]),
        shuffle=False,
        num_workers=int(config["training"]["num_workers"]),
        collate_fn=build_prediction_collate_fn(),
    )


def main():
    args = parse_args()
    runtime_config = load_config(args.config)
    configure_logging(runtime_config)
    prediction_cfg = runtime_config["prediction"]
    split_name = args.split or prediction_cfg["split"]
    tracker = MLflowTracker(runtime_config, stage="prediction")
    LOGGER.info("Loaded prediction config from %s", runtime_config["__config_path__"])

    tracker.start_run(
        run_name=prediction_cfg.get("run_name"),
        extra_tags={"split": split_name, "checkpoint": str(Path(args.checkpoint).name)},
    )
    try:
        checkpoint = torch.load(Path(args.checkpoint), map_location="cpu")
        checkpoint_config = _load_checkpoint_training_config(checkpoint)
        config = _merge_prediction_runtime_config(runtime_config, checkpoint_config)
        dataset = build_dataset(config, split_name)
        if len(dataset) == 0:
            raise RuntimeError(f"No OceanTACO samples matched split '{split_name}'.")
        LOGGER.info("Loaded prediction dataset for split=%s with %s samples", split_name, len(dataset))

        dataloader = DataLoader(
            dataset,
            batch_size=int(prediction_cfg["batch_size"]),
            shuffle=False,
            num_workers=int(config["training"]["num_workers"]),
            collate_fn=build_prediction_collate_fn(),
        )
        reserved_reference_loader = build_reserved_reference_loader(config, split_name, prediction_cfg)

        output_dir = ensure_dir(config["paths"]["predictions_dir"], config)
        LOGGER.info("Writing predictions to %s", output_dir)
        LOGGER.info("Loaded checkpoint from %s", args.checkpoint)
        tracker.log_config()
        tracker.log_metrics({"prediction_dataset_size": float(len(dataset))}, step=0)
        tracker.log_artifact(args.checkpoint, artifact_subdir="checkpoints")

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = build_model(config).to(device)
        model_metadata = checkpoint.get("model_metadata") or describe_model_config(config)
        try:
            model.load_state_dict(checkpoint["model_state_dict"])
        except RuntimeError as exc:
            raise RuntimeError(
                "Checkpoint architecture does not match the prediction model configuration. "
                "Use the training config that produced this checkpoint, or re-save the checkpoint "
                "with an embedded config snapshot by training again with the updated script."
            ) from exc
        model.eval()
        LOGGER.info("Using device=%s for inference model=%s", device, model_metadata)
        input_channel_indices = {
            variable_name: channel_index
            for channel_index, variable_name in enumerate(configured_input_keys(config))
        }

        saved_files = 0
        skipped_batches = 0
        zero_input_batches = 0
        skipped_empty_target_samples = 0
        reserved_metrics = ReservedReferenceMetrics("l3_ssh") if reserved_reference_loader is not None else None
        allow_empty_inputs = bool(prediction_cfg.get("allow_empty_inputs", True))
        with torch.no_grad():
            if reserved_reference_loader is None:
                prediction_iterator = ((batch, None) for batch in dataloader)
            else:
                prediction_iterator = zip(dataloader, reserved_reference_loader)

            for batch_index, (batch, reserved_batch) in enumerate(prediction_iterator):
                present_inputs = [name for name, tensor in batch["inputs"].items() if tensor is not None]
                missing_inputs = [name for name, tensor in batch["inputs"].items() if tensor is None]
                has_any_inputs = bool(present_inputs)
                inputs, targets = batch_to_model_tensors(batch, config, allow_empty_inputs=allow_empty_inputs)
                if inputs is None:
                    skipped_batches += 1
                    LOGGER.warning("Skipping empty prediction batch %s/%s", batch_index + 1, len(dataloader))
                    continue
                if not has_any_inputs:
                    zero_input_batches += 1
                    LOGGER.warning(
                        "Prediction batch %s/%s has no observed inputs. Using zero-filled tensors instead.",
                        batch_index + 1,
                        len(dataloader),
                    )
                elif missing_inputs:
                    LOGGER.warning(
                        "Prediction batch %s/%s is missing inputs %s. The model will receive zero-filled channels for them.",
                        batch_index + 1,
                        len(dataloader),
                        missing_inputs,
                    )
                records = prediction_records(batch, config)
                valid_target_mask = nonempty_target_mask(targets)
                raw_samples = batch.get("raw_samples")
                skipped_in_batch = int((~valid_target_mask).sum().item())
                if skipped_in_batch:
                    skipped_empty_target_samples += skipped_in_batch
                    LOGGER.warning(
                        "Skipping %s empty-target samples in prediction batch %s/%s",
                        skipped_in_batch,
                        batch_index + 1,
                        len(dataloader),
                    )
                if not bool(valid_target_mask.any()):
                    skipped_batches += 1
                    LOGGER.warning(
                        "Skipping prediction batch %s/%s because every target sample is empty.",
                        batch_index + 1,
                        len(dataloader),
                    )
                    continue

                inputs = inputs[valid_target_mask]
                targets = targets[valid_target_mask]
                records = [record for record, keep in zip(records, valid_target_mask.tolist()) if keep]
                raw_samples = None if raw_samples is None else [
                    sample for sample, keep in zip(raw_samples, valid_target_mask.tolist()) if keep
                ]
                reserved_inputs = None
                if reserved_batch is not None:
                    reserved_inputs = batch_input_fields(
                        reserved_batch,
                        config,
                        normalise=False,
                        preserve_missing=True,
                    )
                    if reserved_inputs is not None and "l3_ssh" in reserved_inputs:
                        reserved_inputs["l3_ssh"] = reserved_inputs["l3_ssh"][valid_target_mask]
                input_tensor_cpu = inputs.cpu()
                model_inputs = _denormalise_prediction_tensor(
                    input_tensor_cpu,
                    config["data"]["inputs"],
                    preserve_zero_mask=True,
                ).numpy()
                inputs = inputs.to(device)
                predictions = model(inputs).cpu()
                targets = targets.cpu()
                predictions = _denormalise_prediction_tensor(
                    predictions,
                    config["data"]["targets"],
                    preserve_zero_mask=False,
                ).numpy()
                targets = _denormalise_prediction_tensor(
                    targets,
                    config["data"]["targets"],
                    preserve_zero_mask=True,
                ).numpy()

                batch_size = predictions.shape[0]
                for sample_index in range(batch_size):
                    record = records[sample_index]
                    sample_statuses = (
                        {} if raw_samples is None else infer_sample_input_statuses(raw_samples[sample_index], config)
                    )
                    sample_l3_ssh = None if "l3_ssh" not in sample_statuses else sample_statuses["l3_ssh"]["field"]
                    sample_l4_sst = None if "l4_sst" not in sample_statuses else sample_statuses["l4_sst"]["field"]
                    sample_l3_ssh_np = None if sample_l3_ssh is None else sample_l3_ssh.cpu().numpy()
                    sample_l4_sst_np = None if sample_l4_sst is None else sample_l4_sst.cpu().numpy()
                    l3_ssh_channel = input_channel_indices.get("l3_ssh")
                    l4_sst_channel = input_channel_indices.get("l4_sst")
                    lon_min, lon_max, lat_min, lat_max = record["bbox"]
                    target_date = record["target_date"]
                    save_path = output_dir / (
                        f"{split_name}_{target_date}_"
                        f"lon{lon_min:.2f}_{lon_max:.2f}_lat{lat_min:.2f}_{lat_max:.2f}.npz"
                    )
                    np.savez_compressed(
                        save_path,
                        prediction=predictions[sample_index],
                        target=targets[sample_index],
                        input_l3_ssh=sample_l3_ssh_np,
                        input_l4_sst=sample_l4_sst_np,
                        input_l3_ssh_present=(sample_statuses.get("l3_ssh", {}).get("dataset_status") == "observed"),
                        input_l4_sst_present=(sample_statuses.get("l4_sst", {}).get("dataset_status") == "observed"),
                        input_l3_ssh_dataset_status=sample_statuses.get("l3_ssh", {}).get("dataset_status", "not_configured"),
                        input_l4_sst_dataset_status=sample_statuses.get("l4_sst", {}).get("dataset_status", "not_configured"),
                        input_l3_ssh_model_status=sample_statuses.get("l3_ssh", {}).get("model_status", "not_configured"),
                        input_l4_sst_model_status=sample_statuses.get("l4_sst", {}).get("model_status", "not_configured"),
                        model_input_l3_ssh=(
                            model_inputs[sample_index, :, l3_ssh_channel]
                            if l3_ssh_channel is not None
                            else None
                        ),
                        model_input_l4_sst=(
                            model_inputs[sample_index, :, l4_sst_channel]
                            if l4_sst_channel is not None
                            else None
                        ),
                        model_variant=model_metadata["variant"],
                        model_type=model_metadata["type"],
                        configured_inputs=np.array(model_metadata["input_variables"]),
                        uses_l4_sst_input=bool(model_metadata["uses_l4_sst_input"]),
                        bbox=np.array(record["bbox"], dtype=np.float32),
                        time_range=np.array(record["time_range"]),
                        target_date=target_date,
                    )
                    if reserved_metrics is not None and reserved_inputs is not None and "l3_ssh" in reserved_inputs:
                        target_index = min(int(config["data"]["target_index"]), predictions.shape[1] - 1)
                        reserved_reference = reserved_inputs["l3_ssh"][sample_index, target_index].cpu().numpy()
                        reserved_metrics.update(
                            predictions[sample_index, target_index, 0],
                            reserved_reference,
                            record,
                        )
                    saved_files += 1
                    if config.get("tracking", {}).get("mlflow", {}).get("log_prediction_artifacts", False):
                        tracker.log_artifact(save_path, artifact_subdir="predictions")
                LOGGER.info(
                    "Saved prediction batch %s/%s with %s samples",
                    batch_index + 1,
                    len(dataloader),
                    batch_size,
                )
    finally:
        if "saved_files" in locals():
            reserved_summary = None
            if reserved_metrics is not None:
                reserved_summary = reserved_metrics.write(output_dir)
                if int(reserved_summary["valid_pixels"]) > 0:
                    reserved_mlflow_metrics = {
                        "reserved_l3_ssh_mae": float(reserved_summary["mae"]),
                        "reserved_l3_ssh_rmse": float(reserved_summary["rmse"]),
                        "reserved_l3_ssh_bias": float(reserved_summary["bias"]),
                        "reserved_l3_ssh_valid_pixels": float(reserved_summary["valid_pixels"]),
                    }
                    correlation = float(reserved_summary["correlation"])
                    if np.isfinite(correlation):
                        reserved_mlflow_metrics["reserved_l3_ssh_correlation"] = correlation
                    tracker.log_metrics(reserved_mlflow_metrics, step=0)
            tracker.log_metrics(
                {
                    "saved_prediction_files": float(saved_files),
                    "skipped_prediction_batches": float(skipped_batches),
                    "zero_input_prediction_batches": float(zero_input_batches),
                    "skipped_empty_target_samples": float(skipped_empty_target_samples),
                },
                step=0,
            )
            LOGGER.info(
                "Prediction run finished with saved_prediction_files=%s skipped_prediction_batches=%s "
                "zero_input_prediction_batches=%s skipped_empty_target_samples=%s",
                saved_files,
                skipped_batches,
                zero_input_batches,
                skipped_empty_target_samples,
            )
        tracker.end_run()


if __name__ == "__main__":
    main()
