import argparse
import sys
from pathlib import Path

sys.path.append("src")

import numpy as np
import torch
from torch.utils.data import DataLoader

from src.config_utils import ensure_dir, load_config
from src.oceantaco import batch_to_model_tensors, build_dataset, get_collate_fn, prediction_records
from src.simvp_model import SimVP_Model_no_skip_configurable


def parse_args():
    parser = argparse.ArgumentParser(description="Run SimVP inference on an OceanTACO split.")
    parser.add_argument(
        "--config",
        default="configs/oceantaco.yaml",
        help="Path to the YAML configuration file.",
    )
    parser.add_argument(
        "--checkpoint",
        required=True,
        help="Checkpoint generated by simvp_ddp_training.py.",
    )
    parser.add_argument(
        "--split",
        default=None,
        help="Override the configured prediction split.",
    )
    return parser.parse_args()


def build_model(config):
    grid_cfg = config["data"]["grid"]
    model_cfg = config["model"]
    sequence_length = int(config["data"]["sequence_length"])
    input_channels = len(config["data"]["inputs"])
    target_channels = len(config["data"]["targets"])

    return SimVP_Model_no_skip_configurable(
        in_shape=(sequence_length, input_channels, int(grid_cfg["height"]), int(grid_cfg["width"])),
        out_channels=target_channels,
        model_type=model_cfg["type"],
        hid_S=int(model_cfg["hidden_spatial"]),
        hid_T=int(model_cfg["hidden_temporal"]),
        N_S=int(model_cfg["spatial_depth"]),
        N_T=int(model_cfg["temporal_depth"]),
        drop=float(model_cfg["drop"]),
        drop_path=float(model_cfg["drop_path"]),
    )


def main():
    args = parse_args()
    config = load_config(args.config)
    prediction_cfg = config["prediction"]
    split_name = args.split or prediction_cfg["split"]

    dataset = build_dataset(config, split_name)
    if len(dataset) == 0:
        raise RuntimeError(f"No OceanTACO samples matched split '{split_name}'.")

    dataloader = DataLoader(
        dataset,
        batch_size=int(prediction_cfg["batch_size"]),
        shuffle=False,
        num_workers=int(config["training"]["num_workers"]),
        collate_fn=get_collate_fn(),
    )

    output_dir = ensure_dir(config["paths"]["predictions_dir"], config)
    checkpoint = torch.load(Path(args.checkpoint), map_location="cpu")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = build_model(config).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    with torch.no_grad():
        for batch_index, batch in enumerate(dataloader):
            inputs, targets = batch_to_model_tensors(batch, config)
            records = prediction_records(batch, config)
            inputs = inputs.to(device)
            predictions = model(inputs).cpu().numpy()
            targets = targets.numpy()

            batch_size = predictions.shape[0]
            for sample_index in range(batch_size):
                record = records[sample_index]
                lon_min, lon_max, lat_min, lat_max = record["bbox"]
                target_date = record["target_date"]
                save_path = output_dir / (
                    f"{split_name}_{target_date}_"
                    f"lon{lon_min:.2f}_{lon_max:.2f}_lat{lat_min:.2f}_{lat_max:.2f}.npz"
                )
                np.savez_compressed(
                    save_path,
                    prediction=predictions[sample_index],
                    target=targets[sample_index],
                    bbox=np.array(record["bbox"], dtype=np.float32),
                    time_range=np.array(record["time_range"]),
                    target_date=target_date,
                )
            print(f"saved batch {batch_index + 1}/{len(dataloader)}")


if __name__ == "__main__":
    main()
